jesse_maxwell_prayer:
    resource: "@JesseMaxwellPrayerBundle/Resources/config/routing.yml"
    prefix: /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs