jesse_maxwell_prayer_homepage:
    path:     /hello/{name}
    defaults: { _controller: JesseMaxwellPrayerBundle:Default:index }

frontend:
    resource: @JesseMaxwellPrayerBundle/Controller/FrontendController.php
    type: annotation
