default:
    resource: @JesseMaxwellPrayerBundle/Controller/DefaultController.php
    type: annotation

frontend:
    resource: @JesseMaxwellPrayerBundle/Controller/FrontendController.php
    type: annotation
    prefix: /{username}
