jesse_maxwell_prayer_homepage:
    path:     /hello/{name}
    defaults: { _controller: JesseMaxwellPrayerBundle:Default:index }

_frontend:
    resource: "@JesseMaxwellPrayerBundle/Controller/FrontendController"
    type: annotation
