default:
    resource: @JesseMaxwellPrayerBundle/Controller/DefaultController.php
    type: annotation

list:
    resource: @JesseMaxwellPrayerBundle/Controller/ListController.php
    type: annotation
    prefix: /{username}

action:
    resource: @JesseMaxwellPrayerBundle/Controller/ActionController.php
    type: annotation
    prefix: /{username}