services:
#    jesse_maxwell_prayer.example:
#        class: JesseMaxwell\PrayerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    prayer.responses:
        class: JesseMaxwell\PrayerBundle\Services\ResponseMessage

# Verification:
    prayer.verify_username:
        class: JesseMaxwell\PrayerBundle\EventListener\Authorization\VerifyUsernameListener
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    prayer.verify_action:
        class: JesseMaxwell\PrayerBundle\Services\VerifyUserAction
        arguments: [ @doctrine.orm.entity_manager ]

# Model Classes:
    model.persistence_handler:
        class: JesseMaxwell\PrayerBundle\Entity\PrayerRequestPersistenceHandler
        arguments: [ @doctrine.orm.entity_manager ]