services:
    prayer.default.headers:
        class: JesseMaxwell\PrayerBundle\EventListener\Response\Headers
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
# Validation
    prayer.validator:
        class: JesseMaxwell\PrayerBundle\Validator\Constraints\UniqueTitleValidator
        arguments: [ @request_stack ]
        tags:
            - { name: validator.constraint_validator, alias: unique_title }

# Verification:
    prayer.verify_username:
        class: JesseMaxwell\PrayerBundle\EventListener\Authorization\VerifyUsernameListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    prayer.verify_action:
        class: JesseMaxwell\PrayerBundle\Services\VerifyUserAction
        arguments: [ @request_stack ]