services:
    prayer.responses:
        class: JesseMaxwell\PrayerBundle\Services\ResponseMessage

    prayer.validator:
        class: JesseMaxwell\PrayerBundle\Validator\Constraints\UniqueTitleValidator
        arguments: [ @service_container ]
        tags:
            - { name: validator.constraint_validator, alias: unique_title }

# Verification:
    prayer.verify_username:
        class: JesseMaxwell\PrayerBundle\EventListener\Authorization\VerifyUsernameListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    prayer.verify_action:
        class: JesseMaxwell\PrayerBundle\Services\VerifyUserAction
        arguments: [ @service_container ]